---
abstract: 'Map::Metro map for Oslo'
author:
  - 'Erik Carlsson <info@code301.com>'
build_requires:
  Test::NoTabs: '0'
configure_requires:
  Module::Build::Tiny: '0.039'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.143240'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Map-Metro-Plugin-Map-Oslo
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
requires:
  Map::Metro: '0.1900'
  Moose::Role: '2.0000'
  perl: '5.014000'
resources:
  bugtracker: https://github.com/Csson/p5-Map-Metro-Oslo/issues
  homepage: https://github.com/Csson/p5-Map-Metro-Oslo
  repository: https://github.com/Csson/p5-Map-Metro-Oslo.git
version: '0.1101'
